#!/usr/bin/env python3
# NorsReporter - Automated Penetration Test Report Generator
# License: GPLv3
import os
import sys
import json
from datetime import datetime

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Nors OS - Penetration Test Report</title>
    <style>
        body { font-family: 'Inter', sans-serif; background-color: #0A192F; color: #E6F1FF; margin: 0; padding: 0; }
        .container { max-width: 1000px; margin: 50px auto; background-color: #112240; padding: 40px; border-radius: 10px; box-shadow: 0 10px 30px -10px rgba(0,0,0,0.5); border-top: 5px solid #00B4D8; }
        h1, h2, h3 { color: #00B4D8; }
        .header { text-align: center; border-bottom: 1px solid #233554; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 40px; font-weight: bold; margin-bottom: 10px; }
        .meta-info { display: flex; justify-content: space-between; color: #8892B0; font-size: 14px; }
        .vuln-card { background-color: #0A192F; border-left: 4px solid #FF3366; padding: 20px; margin-bottom: 20px; border-radius: 0 5px 5px 0; }
        .vuln-card.high { border-color: #FF3366; }
        .vuln-card.medium { border-color: #FFB86C; }
        .vuln-card.low { border-color: #F1FA8C; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #233554; }
        th { color: #00B4D8; }
        .footer { text-align: center; margin-top: 50px; font-size: 12px; color: #8892B0; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo">🦅 Nors OS</div>
            <h2>Automated Security Assessment Report</h2>
            <div class="meta-info">
                <span>Target: {{TARGET}}</span>
                <span>Date: {{DATE}}</span>
                <span>Generated by: NorsReporter</span>
            </div>
        </div>

        <div class="section">
            <h3>Executive Summary</h3>
            <p>This report contains the findings of the automated security assessment conducted on {{TARGET}}. The objective was to identify misconfigurations, vulnerabilities, and potential attack vectors.</p>
        </div>

        <div class="section">
            <h3>Vulnerability Findings</h3>
            {{VULN_CARDS}}
        </div>

        <div class="section">
            <h3>Discovered Hosts & Services</h3>
            <table>
                <thead>
                    <tr>
                        <th>IP Address</th>
                        <th>Open Ports / Services</th>
                        <th>OS Guess</th>
                    </tr>
                </thead>
                <tbody>
                    {{HOSTS_TABLE}}
                </tbody>
            </table>
        </div>
        
        <div class="footer">
            Generated securely by Nors OS Ecosystem &copy; 2026
        </div>
    </div>
</body>
</html>
"""

def generate_report(target, findings_json, output_file):
    print(f"[*] Generating report for {target}...")
    
    # Dummy data if no JSON provided
    if not os.path.exists(findings_json):
        findings = {
            "vulnerabilities": [
                {"title": "Anonymous FTP Login Allowed", "severity": "medium", "description": "The FTP service allows anonymous login, potentially exposing sensitive files."},
                {"title": "Outdated Apache Version", "severity": "high", "description": "Apache 2.2.14 is vulnerable to multiple CVEs. Immediate update required."}
            ],
            "hosts": [
                {"ip": "192.168.1.10", "ports": "21/ftp, 80/http, 443/https", "os": "Linux 3.x"},
                {"ip": "192.168.1.15", "ports": "445/smb, 3389/rdp", "os": "Windows Server 2012"}
            ]
        }
    else:
        with open(findings_json, 'r') as f:
            findings = json.load(f)

    # Generate HTML chunks
    vuln_cards_html = ""
    for v in findings.get('vulnerabilities', []):
        vuln_cards_html += f"""
        <div class="vuln-card {v['severity']}">
            <h4 style="margin-top:0;">{v['title']} <span style="font-size:12px; color:#8892B0;">[{v['severity'].upper()}]</span></h4>
            <p>{v['description']}</p>
        </div>
        """

    hosts_html = ""
    for h in findings.get('hosts', []):
        hosts_html += f"<tr><td>{h['ip']}</td><td>{h['ports']}</td><td>{h['os']}</td></tr>"

    html_content = HTML_TEMPLATE.replace("{{TARGET}}", target)
    html_content = html_content.replace("{{DATE}}", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    html_content = html_content.replace("{{VULN_CARDS}}", vuln_cards_html)
    html_content = html_content.replace("{{HOSTS_TABLE}}", hosts_html)

    with open(output_file, 'w') as f:
        f.write(html_content)

    print(f"[+] Report successfully written to {output_file}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: nors_reporter.py <target_name> <output_file.html> [findings.json]")
        sys.exit(1)
    
    target = sys.argv[1]
    output = sys.argv[2]
    json_file = sys.argv[3] if len(sys.argv) > 3 else ""
    
    generate_report(target, json_file, output)
